layout:
    label: Divia 4 paves Citron Anis 01Décembre2015
    previewFileName: divia_4_paves_citron_anis.jpg
    orientation: 0

templates:
    stop:
        file: divia_4_paves_citron_anis.html.twig
